const UserModel = require('./user.model')
const TopicModel = require('./topic.model');
const ArticleModel = require('./article.model');
const ArticleCommentModel = require('./article-comment.model');

const getNotGeneratedFields = (model) => {
    const schema = model.schema.obj;
    const fields = Object.keys(schema).filter(key => !(schema[key].autogenerated === true));
    return fields;
}

const getUpdateableFields = (model) => {
    const schema = model.schema.obj;
    const fields = Object.keys(schema).filter(key => !(schema[key].updateable === false));
    return fields;
}

module.exports = {
    UserModel,
    TopicModel,
    ArticleModel,
    ArticleCommentModel,
    getNotGeneratedFields,
    getUpdateableFields,
}